# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ensure_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ensure_window(object):
    def setupUi(self, ensure_window):
        ensure_window.setObjectName("ensure_window")
        ensure_window.resize(219, 73)
        ensure_window.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(ensure_window)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 201, 61))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushbutton_yes = QtWidgets.QPushButton(self.widget)
        self.pushbutton_yes.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushbutton_yes.setObjectName("pushbutton_yes")
        self.horizontalLayout.addWidget(self.pushbutton_yes)
        self.pushbutton_no = QtWidgets.QPushButton(self.widget)
        self.pushbutton_no.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushbutton_no.setObjectName("pushbutton_no")
        self.horizontalLayout.addWidget(self.pushbutton_no)
        self.verticalLayout.addLayout(self.horizontalLayout)
        ensure_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(ensure_window)
        QtCore.QMetaObject.connectSlotsByName(ensure_window)

    def retranslateUi(self, ensure_window):
        _translate = QtCore.QCoreApplication.translate
        ensure_window.setWindowTitle(_translate("ensure_window", "are you sure?"))
        self.label.setText(_translate("ensure_window", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">delete all labels?</span></p></body></html>"))
        self.pushbutton_yes.setText(_translate("ensure_window", "yes"))
        self.pushbutton_no.setText(_translate("ensure_window", "no"))
