# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_app_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 855)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushbutton_prev = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_prev.setMinimumSize(QtCore.QSize(0, 30))
        self.pushbutton_prev.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 255, 255);\n"
"    border-radius: 9px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.pushbutton_prev.setObjectName("pushbutton_prev")
        self.verticalLayout.addWidget(self.pushbutton_prev)
        self.pushbutton_next = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_next.setMinimumSize(QtCore.QSize(0, 30))
        self.pushbutton_next.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 255, 255);\n"
"    border-radius: 9px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.pushbutton_next.setObjectName("pushbutton_next")
        self.verticalLayout.addWidget(self.pushbutton_next)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.pushbutton_add_label = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_add_label.setMinimumSize(QtCore.QSize(0, 30))
        self.pushbutton_add_label.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 255, 255);\n"
"    border-radius: 9px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.pushbutton_add_label.setObjectName("pushbutton_add_label")
        self.verticalLayout.addWidget(self.pushbutton_add_label)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineedit_key = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_key.setMinimumSize(QtCore.QSize(0, 30))
        self.lineedit_key.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineedit_key.setClearButtonEnabled(True)
        self.lineedit_key.setObjectName("lineedit_key")
        self.gridLayout_2.addWidget(self.lineedit_key, 0, 1, 1, 1)
        self.lineedit_value = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_value.setMinimumSize(QtCore.QSize(0, 30))
        self.lineedit_value.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineedit_value.setClearButtonEnabled(True)
        self.lineedit_value.setObjectName("lineedit_value")
        self.gridLayout_2.addWidget(self.lineedit_value, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 255, 127);\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: rgb(170, 255, 127);\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.pushbutton_delete_label = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_delete_label.setMinimumSize(QtCore.QSize(0, 30))
        self.pushbutton_delete_label.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 255, 255);\n"
"    border-radius: 9px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.pushbutton_delete_label.setObjectName("pushbutton_delete_label")
        self.verticalLayout.addWidget(self.pushbutton_delete_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("QLabel {\n"
"    background-color: rgb(0, 255, 127);\n"
"}")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lineedit_delete_key = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_delete_key.setMinimumSize(QtCore.QSize(0, 30))
        self.lineedit_delete_key.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineedit_delete_key.setClearButtonEnabled(True)
        self.lineedit_delete_key.setObjectName("lineedit_delete_key")
        self.horizontalLayout_2.addWidget(self.lineedit_delete_key)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushbutton_delete_all_label = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_delete_all_label.setMinimumSize(QtCore.QSize(0, 30))
        self.pushbutton_delete_all_label.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 255, 255);\n"
"    border-radius: 9px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.pushbutton_delete_all_label.setObjectName("pushbutton_delete_all_label")
        self.verticalLayout.addWidget(self.pushbutton_delete_all_label)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.lineedit_turn_to_image = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_turn_to_image.setMinimumSize(QtCore.QSize(0, 30))
        self.lineedit_turn_to_image.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineedit_turn_to_image.setObjectName("lineedit_turn_to_image")
        self.verticalLayout.addWidget(self.lineedit_turn_to_image)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout.addWidget(self.line_7)
        self.pushbutton_subsidence = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_subsidence.setMinimumSize(QtCore.QSize(0, 30))
        self.pushbutton_subsidence.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 170, 127);\n"
"    border-radius: 9px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.pushbutton_subsidence.setObjectName("pushbutton_subsidence")
        self.verticalLayout.addWidget(self.pushbutton_subsidence)
        self.pushbutton_deformation = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_deformation.setMinimumSize(QtCore.QSize(0, 30))
        self.pushbutton_deformation.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 170, 127);\n"
"    border-radius: 9px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.pushbutton_deformation.setObjectName("pushbutton_deformation")
        self.verticalLayout.addWidget(self.pushbutton_deformation)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout.addWidget(self.line_6)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(700, 0))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: rgb(170, 170, 255);\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.textbrowser_labels = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textbrowser_labels.sizePolicy().hasHeightForWidth())
        self.textbrowser_labels.setSizePolicy(sizePolicy)
        self.textbrowser_labels.setMinimumSize(QtCore.QSize(0, 0))
        self.textbrowser_labels.setMaximumSize(QtCore.QSize(200, 16777215))
        self.textbrowser_labels.setObjectName("textbrowser_labels")
        self.verticalLayout_2.addWidget(self.textbrowser_labels)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: rgb(170, 170, 255);\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.textbrowser_images = QtWidgets.QTextBrowser(self.centralwidget)
        self.textbrowser_images.setMaximumSize(QtCore.QSize(200, 16777215))
        self.textbrowser_images.setOpenExternalLinks(False)
        self.textbrowser_images.setObjectName("textbrowser_images")
        self.verticalLayout_2.addWidget(self.textbrowser_images)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 23))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.menufile.addAction(self.actionopen)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushbutton_prev.setText(_translate("MainWindow", "prev image"))
        self.pushbutton_next.setText(_translate("MainWindow", "next imgae"))
        self.pushbutton_add_label.setText(_translate("MainWindow", "add label"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic;\">key</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic;\">value</span></p></body></html>"))
        self.pushbutton_delete_label.setText(_translate("MainWindow", "delete label"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic;\">key</span></p></body></html>"))
        self.pushbutton_delete_all_label.setText(_translate("MainWindow", "delete all label"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic;\">turn to image</span></p></body></html>"))
        self.pushbutton_subsidence.setText(_translate("MainWindow", "subsidence"))
        self.pushbutton_deformation.setText(_translate("MainWindow", "deformation"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-style:italic;\">image</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic;\">labels</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic;\">images</span></p></body></html>"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.actionopen.setText(_translate("MainWindow", "open"))
